name: 開始native
on:
  workflow_dispatch: #手動觸發
jobs:
 OK:
  runs-on: ubuntu-latest
  steps:
   - name: 安裝OpenGL
     run: sudo apt install -y libopengl0
   - name: 安裝Node依賴
     run: npm install @maplibre/maplibre-gl-native@^6.4.1 sharp@^0.35.4
   - name: 執行node
     run: curl -fsSL '${{secrets.JS}}'|xvfb-run -a node
